---
title: "Hotel bookings - factors"
author: "Simon Taylor"
date: "`r Sys.Date()`"
output: html_document
---

```{r load-pkg, message = FALSE}
library(tidyverse)
```


```{r load-data, message = FALSE}
hotels <- read_csv("data/hotels.csv")
```

First, knit the document and view the following visualisation. 

-   How are the months ordered? 
-   What would be a better order? 

Reorder the months on the x-axis (levels of `arrival_date_month`) in a way that makes more sense. You will want to use a function from the [**forcats**](https://forcats.tidyverse.org/reference/index.html) package.

```{r plot, fig.width=10}
hotels %>%
  group_by(hotel, arrival_date_month) %>%   # group by hotel type and arrival month
  summarise(mean_adr = mean(adr)) %>%       # calculate mean adr for each group
  ggplot(aes(
    x = arrival_date_month,                 # x-axis = arrival_date_month
    y = mean_adr,                           # y-axis = mean_adr calculated above
    group = hotel,                          # group lines by hotel type
    color = hotel)                          # and color by hotel type
    ) +
  geom_line() +                             # use lines to represent data
  theme_minimal() +                         # use a minimal theme
  labs(x = "Arrival month",                 # customize labels
       y = "Mean ADR (average daily rate)",
       title = "Comparison of resort and city hotel prices across months",
       subtitle = "Resort hotel prices soar in the summer while ciry hotel prices remain relatively constant throughout the year",
       color = "Hotel type")
```
